# Generated by Django 3.2.12 on 2022-03-10 05:05

from django.db import migrations, models
import media.validators


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0005_alter_media_media_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='media_file',
            field=models.FileField(upload_to='media/', validators=[media.validators.FileValidator(content_types=('image/png', 'image/jpeg', 'image/gif', 'video/mp4'))]),
        ),
    ]
